first commit
shugoStr/ruby-practices pull request #2
Opened 2021-04-02 11:39 UTC by MensExperience

課題を提出致します。
ご確認よろしくお願い致します！

2021-04-08 04:07 UTC, u1tnk requested changes

2021-04-08 04:07 UTC, u1tnk commented on 02.calendar/.gitignore
> +.DS_Store
めっちゃ細かいですけど、こういうのはPRと分けとくと良いですね。
レビュワーに見て欲しいものでは無いと思いますので。
あと、これが `first commit`になっているのは良いですがカレンダー本体にはちゃんとコミットメッセージを書くと良かったですね。
参考: https://docs.komagata.org/5744

2021-04-08 04:07 UTC, u1tnk commented on 02.calendar/calendar.rb
> +  if n.day < 10
一桁のときのpaddingですね。 右詰めにするメソッドがあってそれを使うと処理を共通にできるので探してみましょう。
ifは書かずに済むなら減らした方が読みやすいです。

2021-04-08 04:07 UTC, u1tnk commented on 02.calendar/calendar.rb
> +      print(" " + "#{n.day} \n")
こちらは ifは必要になりますが、共通で繰り返している部分が多いですね。

共通の部分＋ `print "\n"` にするとifの対象が減って良いですね。

2021-04-08 11:19 UTC, MensExperience commented on 02.calendar/.gitignore
> +.DS_Store
ご指摘ありがとうございます！
確かに、こちら不要なものでした。今後気をつけます。
コミットメッセージについても承知しました。
勝手に最初のコミットは、``first commit``で決まっているのかと思い込んでいました。。
参考URLありがとうございます。

2021-04-08 11:20 UTC, MensExperience commented on 02.calendar/calendar.rb
> +  if n.day < 10
右詰めメソッド確認します。
> ifは書かずに済むなら減らした方が読みやすいです。
確かに仰る通りですね。ありがとうございます！

2021-04-08 11:22 UTC, MensExperience commented on 02.calendar/calendar.rb
> +      print(" " + "#{n.day} \n")
- 共通化をしてコード量を減らす
承知しました。再度コード見直します！

2021-04-08 15:20 UTC, MensExperience commented on 02.calendar/.gitignore
> +.DS_Store
ちなみに質問よろしいでしょうか？
普段自分は、①git add .　②git commit -m "メッセージ"　②git push Origin Head　と操作しています。
上でご説明頂いたのは、一旦 ``.gitignore`` を``first commit``し、課題を適切なコミットメッセージを付けてプッシュする。
PR時には、課題ファイルのみを選択し（画面にて選択できるのでしょうか？）、レビューをお願いする。
上記の認識で大丈夫でしょうか。
以上、よろしくお願い致します！

2021-04-08 15:21 UTC, MensExperience commented on 02.calendar/calendar.rb
> +  if n.day < 10
右詰め、Rubyにてググりまして、``rjust``メソッドを見つけました。
こちらで改修を行いました。

2021-04-08 15:23 UTC, MensExperience commented on 02.calendar/calendar.rb
> +      print(" " + "#{n.day} \n")
``rjust``のおかげで、1桁判定が不要になり、
多かったifが減ってスッキリできたように思えます。

2021-04-09 01:04 UTC, u1tnk commented on 02.calendar/.gitignore
> +.DS_Store
pushする手順は大丈夫です 🙆‍♀️ 

> PR時には、課題ファイルのみを選択し（画面にて選択できるのでしょうか？）、

これはできません。PRには マージ先のブランチとの差分が表示されるので、この場合レビューされる必要の無いものは直接mainにpushするか別PRで先にマージしておけば良いです。
課題なのでどっちでも良いですが、実業務だと前者はレビュー無しにmainにマージされてしまうので避けられます。

2021-04-09 01:07 UTC, u1tnk commented on 02.calendar/calendar.rb
> +  if n.saturday?
惜しい！

めちゃめちゃスッキリしたのですが、あと一歩でした。
改行の部分だけが違うので、他はifから出しましょう。ちなみにelseで `" "`を出力していますが、行末なので不要ですよね？
そうであれば ifで制御するのは改行の出力のみになるはずです 💪

2021-04-09 03:37 UTC, MensExperience commented on 02.calendar/.gitignore
> +.DS_Store
ご回答ありがとうございます！🙏

> 実業務だと前者はレビュー無しにmainにマージされてしまうので避けられます。

なるほど、、承知しました。
次回の課題の際は、こちらの方法で試してみます。

2021-04-09 03:41 UTC, MensExperience commented on 02.calendar/calendar.rb
> +  if n.saturday?
うお！あと一歩考えが足りませんでした。😭
ほとんど答えに近いコメントを頂いているので、再度見直してみます！

2021-04-09 03:57 UTC, MensExperience commented on 02.calendar/calendar.rb
> +  if n.saturday?
旧：ifで土曜日用の出力（日数+改行）、それ以外（日数）
現在：ifを土曜か判定し真なら改行
目からうろこでした。。判断がシンプル！
になり分かりやすくなりました。

（これで正解でなければ恥ずかしいですが・・・ｗ）
ご確認、よろしくお願い致します！

2021-04-09 04:04 UTC, MensExperience commented on 02.calendar/calendar.rb
> +  if n.saturday?
ちなみにすみません、また質問いいでしょうか？
今回コミットメッセージを少しミスってしまい、``-m``という余計な文字が入っています。

以下修正方法としてググってみました。
https://docs.github.com/ja/github/committing-changes-to-your-project/changing-a-commit-message

状況として、
・すでにプッシュ済み

ただし、
・リポジトリの履歴が変更されるため、フォースプッシュは推奨されない

コミットメッセージの修正方法としては、
・コミットメッセージを変更し、再度プッシュし直す
が良いでしょうか？
その他方法あれば、よろしくお願い致します！🙏

2021-04-09 06:46 UTC, u1tnk commented on 02.calendar/calendar.rb
> +  if n.saturday?
> ・リポジトリの履歴が変更されるため、フォースプッシュは推奨されない

これはその通りなのですが、コミットメッセージのミスなどではせざるを得ませんね。
プロジェクトごとの規約や文化がありますが、私としては 「PRマージ前の自分しか触っていないコード」でしたら注意しつつ `git commit --amend` 等で修正してフォースプッシュで対応します。
mainにマージされちゃってどうしても修正したかったらプロジェクトメンバー全員に周知して許可を取ってからフォースプッシュするしか無いので。

2021-04-09 06:49 UTC, u1tnk commented on 02.calendar/calendar.rb
> +  if n.saturday?
あ、見逃してました、修正内容は問題無いです！
最初に比べるとめちゃくちゃ読みやすくなりました ✨ 
 仕事のプログラムは書く事よりも読む方が何倍も多い上寿命も長いので読みやすさはとても大事です。

あともう十分なのでOKですが、よくある構文としては

`print "\n" if  n.saturday?`

と後置ifで書くと一行で済みますよ。これは今後の参考まで。

2021-04-09 11:26 UTC, MensExperience commented on 02.calendar/calendar.rb
> +  if n.saturday?
> 「PRマージ前の自分しか触っていないコード」でしたら注意しつつ git commit --amend 等で修正してフォースプッシュで対応します。

ありがとうございます。こちら今後別の個人のリポジトリで試しにやってみたいと思います。

> 後置if
勉強になります。RubyはJavaと比べて知っていると便利なメソッドやスッキリしたコードが書けて楽しいですね！
今後ともよろしくお願い致します。

2021-04-09 11:45 UTC, merged

2021-04-09 12:53 UTC, u1tnk commented on 02.calendar/calendar.rb
> +  if n.saturday?
僕もJavaからrubyに来たので同じ感想だった事を思いだしました。
読みやすくする工夫がたくさんで楽しいですよね  ✨